"""The script: word counts and times at the pace class, the generated script.md, and its PDF.

Before stage 4 the script is written by hand in 3-script/script.md, one `### <ID>. <title> - m:ss`
section per beat; it is only timed. From stage 4 on the storyboard holds the text, and script.md is
generated from it, so the words rehearsed are the words the deck shows, frame by frame.
"""

import re
import subprocess
import sys

from .project import Talk
from .storyboard import Storyboard, spoken

PACES = {"slow": 120, "normal": 135, "fast": 150}
MARKER = "by `mpp script`. Do not edit this file"  # in every generated script.md
HEADING = re.compile(r"^###\s+([A-Za-z_]\w*)\.\s+(.*?)\s+-\s+(\d+:\d{2}|[\d.]+\s*min)\s*$")


def pace(talk: Talk) -> tuple[str, int]:
    name = talk.config().get("pace", "normal")
    if name not in PACES:
        raise ValueError(f"talk.toml: pace must be one of {', '.join(PACES)}, not {name!r}")
    return name, PACES[name]


def mmss(sec: float) -> str:
    sec = int(round(sec))
    return f"{sec // 60}:{sec % 60:02d}"


def seconds(budget: str) -> float:
    if ":" in budget:
        m, s = budget.split(":")
        return int(m) * 60 + int(s)
    return float(budget.replace("min", "")) * 60


# ---------------------------------------------------------------- timing
def rows_from_storyboard(sb: Storyboard) -> list[dict]:
    return [
        {
            "id": b,
            "title": sb.beat(b).get("title", b),
            "act": sb.beat(b).get("act"),
            "words": sb.words(b),
            "budget": sb.beat(b).get("budget_s", 0),
        }
        for b in sb.order
    ]


def rows_from_markdown(text: str) -> list[dict]:
    """Beats of a hand-written script.md. Sections without a time budget are alternate takes: not counted."""
    rows, act, cur = [], None, None
    for line in text.splitlines():
        if line.startswith("## "):
            act, cur = line[3:].strip(), None
        elif line.startswith("### "):
            m = HEADING.match(line)
            cur = {"id": m[1], "title": m[2], "act": act, "words": 0, "budget": seconds(m[3])} if m else None
            if cur:
                rows.append(cur)
        elif cur and line.strip() and not line.lstrip().startswith(">"):
            cur["words"] += len(spoken(line).split())
    return rows


def report(talk: Talk, rows: list[dict]) -> str:
    name, wpm = pace(talk)
    slot = talk.config().get("slot_min", 0) * 60
    out, act, act_words, act_budget = [], object(), 0, 0

    def close_act():
        if act_words or act_budget:
            out.append(
                f"{'':6}{'act total':<37} {act_words:5} words  {mmss(act_words / wpm * 60):>6} / {mmss(act_budget)}"
            )

    for r in rows:
        if r["act"] != act:
            close_act()
            act, act_words, act_budget = r["act"], 0, 0
            out.append(f"act {act}")
        said = r["words"] / wpm * 60
        flag = "OVER" if said > r["budget"] + 5 else "    "
        out.append(
            f"{flag}  {r['id']:<8} {r['title'][:28]:<28} {r['words']:5} words  {mmss(said):>6} / {mmss(r['budget'])}"
        )
        act_words += r["words"]
        act_budget += r["budget"]
    close_act()
    words = sum(r["words"] for r in rows)
    said, budget = words / wpm * 60, sum(r["budget"] for r in rows)
    out += [
        "",
        f"{words} words: {mmss(said)} spoken at {name} pace ({wpm} wpm); "
        f"budgets sum to {mmss(budget)}; the slot is {mmss(slot)}.",
    ]
    if slot and said > slot:
        out.append(f"Over the slot by {mmss(said - slot)}: cut whole beats, not words.")
    return "\n".join(out)


# ---------------------------------------------------------------- the generated script
def markdown(talk: Talk, sb: Storyboard) -> str:
    name, wpm = pace(talk)
    cfg = talk.config()
    words = sum(sb.words(b) for b in sb.order)
    out = [
        f"# {cfg.get('title') or 'Talk'}: script",
        "",
        "Generated from `4-visual/storyboard.toml` by `mpp script`. Do not edit this file: change the",
        "storyboard and regenerate, so the script and the deck cannot drift apart.",
        "",
        f"Pace: {name} ({wpm} wpm). Spoken: {mmss(words / wpm * 60)}. Slot: {cfg.get('slot_min', '?')} min.",
        "",
        "Each `>` line is a click: the slide number, its ID, the headline on screen, and the words that",
        "fire it. The paragraphs under it are said while that slide is up.",
    ]
    act = None
    for frame in sb.frames():
        beat = sb.beat(frame.beat)
        if frame.beat in sb.backup and frame.beat == sb.backup[0] and frame.index == 1:
            out += ["", "## Backup", "", "After the last slide, for questions."]
        elif frame.beat in sb.order and beat.get("act") != act:
            act = beat.get("act")
            out += ["", f"## Act {act}: {sb.acts.get(act, '')}"]
        if frame.index == 1:
            budget = f" - {mmss(beat.get('budget_s', 0))}" if frame.beat in sb.order else ""
            out += ["", f"### {frame.beat}. {beat.get('title', frame.beat)}{budget}"]
        cue = f'> **{frame.number}** ({frame.id}) · slide: "{" ".join(frame.head.split())}"'
        trigger = " ".join(frame.trigger.split())
        cue += f" · {trigger.strip('()')}" if trigger.startswith("(") else f' · click on: "{trigger}"'
        out += ["", cue, ""]
        said = " ".join(frame.narration.split())
        out.append(f"> {said.strip('()')}" if said.startswith("(") and said.endswith(")") else said)
    return "\n".join(out) + "\n"


def fountain(talk: Talk, sb: Storyboard) -> str:
    """The script as a screenplay: a scene per beat, an action line per click, the narration as dialogue."""
    cfg = talk.config()
    name, wpm = pace(talk)
    speaker = (cfg.get("speaker") or "Speaker").upper()
    words = sum(sb.words(b) for b in sb.order)
    out = [
        f"Title: {cfg.get('title') or 'Talk'}",
        f"Author: {cfg.get('speaker', '')}",
        f"Draft date: {cfg.get('date', '')}",
        f"Contact: {mmss(words / wpm * 60)} spoken at {name} pace ({wpm} wpm)",
        "",
    ]
    act, t = None, 0.0
    for frame in sb.frames():
        beat = sb.beat(frame.beat)
        if frame.beat in sb.order and beat.get("act") != act:
            act = beat.get("act")
            out += ["", f"> ACT {act}: {sb.acts.get(act, '').upper()} <", ""]
        if frame.beat in sb.backup and frame.beat == sb.backup[0] and frame.index == 1:
            out += ["", "> BACKUP <", ""]
        if frame.index == 1:
            budget = beat.get("budget_s", 0) if frame.beat in sb.order else 0
            span = f" ({mmss(t)}-{mmss(t + budget)})" if frame.beat in sb.order else ""
            out += ["", f".{frame.beat} {beat.get('title', frame.beat).upper()}{span}", ""]
            t += budget
        trigger = " ".join(frame.trigger.split())
        cue = f'!{frame.number} ({frame.id}): "{" ".join(frame.head.split())}"'
        cue += f" [{trigger.strip('()')}]" if trigger.startswith("(") else f' [click on "{trigger}"]'
        out += [cue, ""]
        said = " ".join(frame.narration.split())
        if said.startswith("(") and said.endswith(")"):
            out += [f"!{said}", ""]
        elif said:
            out += [f"@{speaker}", said, ""]
    return "\n".join(out) + "\n"


def target(talk: Talk, rel: str):
    """Where a file generated from the storyboard goes: the variant's folder if the variant has its
    own storyboard, else global's (the variant reads global's copy)."""
    if talk.variant and (talk.root / talk.layers[0] / "4-visual" / "storyboard.toml").exists():
        return talk.root / talk.layers[0] / rel
    return talk.root / "talk" / "global" / rel


def run(talk: Talk, pdf: bool = False, from_storyboard: bool = False) -> str:
    """Time the script; regenerate script.md from the storyboard; write the PDF on request.

    A hand-written script.md (stage 3: no generated marker) is only timed, never overwritten, even
    when a storyboard exists: the template ships a placeholder one. `from_storyboard` hands the
    script over to the storyboard, once stage 4 has moved its text there.
    """
    text = talk.read("3-script/script.md")
    if text is not None and MARKER not in text and not from_storyboard:
        if pdf:
            raise RuntimeError(
                "script.md is hand-written; the PDF is made from the storyboard. Once its text is in the "
                "storyboard (stage 4), run `mpp script --from-storyboard`"
            )
        return (
            report(talk, rows_from_markdown(text))
            + "\n\nscript.md is hand-written, so it was only timed. Once its text is in the storyboard "
            "(stage 4), `mpp script --from-storyboard` replaces it with the generated script."
        )
    sb = talk.storyboard()
    problems = sb.problems()
    if problems:
        raise ValueError("the storyboard has problems:\n  " + "\n  ".join(problems))
    md = target(talk, "3-script/script.md")
    md.parent.mkdir(parents=True, exist_ok=True)
    md.write_text(markdown(talk, sb))
    lines = [report(talk, rows_from_storyboard(sb)), "", f"wrote {md.relative_to(talk.root)}"]
    if pdf:
        out = talk.exports()
        out.mkdir(parents=True, exist_ok=True)
        (out / "script.fountain").write_text(fountain(talk, sb))
        r = subprocess.run(
            [
                sys.executable,
                "-c",
                "import sys; from screenplain.main import main; main(sys.argv[1:])",
                str(out / "script.fountain"),
                str(out / "script.pdf"),
            ],
            capture_output=True,
            text=True,
        )
        if r.returncode:
            raise RuntimeError(f"screenplain failed:\n{r.stderr}")
        lines.append(f"wrote {(out / 'script.pdf').relative_to(talk.root)}")
    return "\n".join(lines)
